server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /accounts-service
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts
  datasource:
    url: jdbc:postgresql://localhost:5433/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: accounts
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/