server:
  port: 8900
spring:
  mvc:
    servlet:
      path: /accounts-service
  application:
    name: accounts-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 