server:
  port: 8081
spring:
  mvc:
    servlet:
      path: /accounts-service
  application:
    name: accounts-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 