server:
  port: 8082
spring:
  mvc:
    servlet:
      path: /gateway-service
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
