server:
  port: 8084
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts-service/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR,SERVICE_UNAVAILABLE,BAD_GATEWAY
                methods: GET,POST,PUT,DELETE
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: accounts-service-cb
                fallbackUri: forward:/fallback/accounts