server:
  port: 8083
spring:
  mvc:
    servlet:
      path: /blocker-service
  application:
    name: blocker-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 