server:
  port: 8084
spring:
  mvc:
    servlet:
      path: /cash-service
  application:
    name: cash-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 