server:
  port: 8761
spring:
  mvc:
    servlet:
      path: /eureka-server
  application:
    name: eureka-server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
management:
  endpoints:
    web:
      exposure:
        include: health,info