server:
  port: 8087
spring:
  mvc:
    servlet:
      path: /exchange-generator-service
  application:
    name: exchange-generator-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/