server:
  port: 8086
spring:
  mvc:
    servlet:
      path: /exchange-service
  application:
    name: exchange-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/