server:
  port: 8088
spring:
  mvc:
    servlet:
      path: /front-service
  application:
    name: front-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 