server:
  port: 8089
spring:
  mvc:
    servlet:
      path: /notifications-service
  application:
    name: notifications-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/