server:
  port: 8090
spring:
  mvc:
    servlet:
      path: /transfer-service
  application:
    name: transfer-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/